name: memer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.3.1"

dependencies:
  cached_network_image: ^3.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.4
  fluttertoast: ^8.0.9
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  isar: 2.5.0
  isar_flutter_libs: 2.5.0
  path_provider: ^2.0.11
  shimmer: ^2.0.0
  image_downloader: ^0.31.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: 2.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
